POST http://localhost:8080/v1/cart
Content-Type: application/json

{
  "items": [
    {
      "productId": "123",
      "quantity": 1
    },
    {
      "productId": "456",
      "quantity": 2
    }
  ]
}